version: '3.8'
services:
  pgsql:
    container_name: postgresql
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
  
  api:
    container_name: "school"
    depends_on:
      - pgsql
    environment:
      PORT: 9000

      DATABASE_DRIVER: postgres
      DATABASE_URL: postgres://postgres:postgres@pgsql:5432/school?sslmode=disable
    ports:
      - "9000:9000"
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: unless-stopped

volumes:
  postgres: