// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createSchoolMaterialStmt, err = db.PrepareContext(ctx, createSchoolMaterial); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSchoolMaterial: %w", err)
	}
	if q.getSchoolMaterialArrayStmt, err = db.PrepareContext(ctx, getSchoolMaterialArray); err != nil {
		return nil, fmt.Errorf("error preparing query GetSchoolMaterialArray: %w", err)
	}
	if q.getSchoolMaterialByIDStmt, err = db.PrepareContext(ctx, getSchoolMaterialByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSchoolMaterialByID: %w", err)
	}
	if q.updateSchoolMaterialStmt, err = db.PrepareContext(ctx, updateSchoolMaterial); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateSchoolMaterial: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createSchoolMaterialStmt != nil {
		if cerr := q.createSchoolMaterialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSchoolMaterialStmt: %w", cerr)
		}
	}
	if q.getSchoolMaterialArrayStmt != nil {
		if cerr := q.getSchoolMaterialArrayStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSchoolMaterialArrayStmt: %w", cerr)
		}
	}
	if q.getSchoolMaterialByIDStmt != nil {
		if cerr := q.getSchoolMaterialByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSchoolMaterialByIDStmt: %w", cerr)
		}
	}
	if q.updateSchoolMaterialStmt != nil {
		if cerr := q.updateSchoolMaterialStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateSchoolMaterialStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                         DBTX
	tx                         *sql.Tx
	createSchoolMaterialStmt   *sql.Stmt
	getSchoolMaterialArrayStmt *sql.Stmt
	getSchoolMaterialByIDStmt  *sql.Stmt
	updateSchoolMaterialStmt   *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                         tx,
		tx:                         tx,
		createSchoolMaterialStmt:   q.createSchoolMaterialStmt,
		getSchoolMaterialArrayStmt: q.getSchoolMaterialArrayStmt,
		getSchoolMaterialByIDStmt:  q.getSchoolMaterialByIDStmt,
		updateSchoolMaterialStmt:   q.updateSchoolMaterialStmt,
	}
}
