// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSchoolMaterial(ctx context.Context, arg CreateSchoolMaterialParams) (SchoolMaterial, error)
	GetSchoolMaterialArray(ctx context.Context, arg GetSchoolMaterialArrayParams) ([]SchoolMaterial, error)
	GetSchoolMaterialByID(ctx context.Context, materialID uuid.UUID) (SchoolMaterial, error)
	UpdateSchoolMaterial(ctx context.Context, arg UpdateSchoolMaterialParams) (SchoolMaterial, error)
}

var _ Querier = (*Queries)(nil)
