# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/master/configuration-schema.json
package: api
output: internal/api/server.gen.go
generate:
  echo-server: true
output-options:
  initialism-overrides: true
  # nullable-type: true