version: "2"
sql:
  - engine: postgresql
    # database:
      # uri: 'postgres://postgres:postgres@127.0.0.1:5432/schoolmat'
    queries:
      - ../sql/queries
    schema:
      - ../sql/migrations
    gen:
      go:
        package: db
        out: ../internal/storage/db
        sql_package: "database/sql"
        emit_interface: true
        emit_prepared_queries: true
        emit_pointers_for_null_types: true
          